apiVersion: v1
kind: Service
metadata:
  name: holdings
  labels:
    app: holdings
spec:
  type: NodePort  # Change to ClusterIP or NodePort if needed
  selector:
    app: holdings
  ports:
  - port: 80
    targetPort: 8001
    nodePort: 30888 
    protocol: TCP