apiVersion: v1
kind: Service
metadata:
  name: market-data
  labels:
    app: market-data
spec:
  type: ClusterIP  # Change to ClusterIP or NodePort if needed
  selector:
    app: market-data
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP